/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinSample3

import test.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    val tim = Player("Tim")
    println(tim.name)
    println(tim.lives)
    println(tim.level)
    println(tim.score)

    //println("How old are you: ")
    //val age = readLine()!!
    //println("Your age is $age")
}
